galaxy_info:
  role_name: avise_csp
  author: Avi Networks
  description: Ansible Role to setup Avi Service Engine on CSP Cloud
  company: Avi Networks
  license: Apache-2.0
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
    - xenial
  galaxy_tags:
    - avi
    - controller
    - avicontroller
    - avisdk
    - avinetworks
    - networks
    - load
    - balancer
    - sdk
    - lbaas
    - lb
    - virtualserver
    - cloud
    - loadbalancer
    - gslb
    - csp
    - cisco
dependencies:
  - { role: avinetworks.avisdk }
